- name: Start database and install packages
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:

  - name: update packages
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install postgres, Docker and dependencies
    apt:
      name: 
        - postgresql-12
        - postgresql-client-12
        - acl
        - python3-pip
#        - ufw
#        - docker.io
      state: latest

#  - name: Start docker service
#    service:
#      name: docker
#      state: started
      
#  - name: Allow db server in ufw
#    ufw:
#      rule: allow
#      port: "5432"
#      proto: tcp
    
#  - name: Allow db server in ufw
#    ufw:
#      rule: allow
#      port: "80"
#      proto: tcp

#  - name: Allow db server in ufw
#    ufw:
#      rule: allow
#      port: "5434"
#      proto: tcp 
#  - name: Create PostgreSQL container
#    docker_container:
#      name: postgres
#      image: postgres:12
#      state: started
#      recreate: yes
#      ports:
#        - "5432:5432"
        
  - name: Start and enable postgres on startup
    service: "name={{ item }} state=started enabled=yes"
    with_items:
      - postgresql

  - name: Install psycopg2
    pip:
      name: psycopg2-binary
      state: latest

  - name: Create webserver db
    postgresql_db:
      state: present
      #name: "{{ db_name }}"
      name: webbi
    become: yes
    become_user: postgres

  - name: Create db user
    postgresql_user:
      state: present
      #name: "{{ db_user }}"
      name: webbi
      #password: "{{ db_password }}"
      password: webbi
    become: yes
    become_user: postgres

  - name: Grant db user access to webserver db
    postgresql_privs:
      type: database
      #database: "{{ db_name }}"
      database: webbi
      #roles: "{{ db_user }}"
      roles: webbi
      grant_option: no
      privs: all
    become: yes
    become_user: postgres
